import React from 'react'

function About() {
  return (
      <>
      <div className='container my-3' style={{fontSize:"1.7rem"}}>
    <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam saepe in cum voluptatum deserunt aut? Harum totam laudantium repudiandae sed modi ullam sunt deserunt nostrum, est, expedita qui blanditiis officia veritatis voluptatem consequuntur eum veniam ipsam assumenda! Iste quia ipsum sunt ullam dolore, omnis, repudiandae sed dolorum placeat corporis mollitia adipisci quaerat tenetur. Fuga placeat magni modi dicta sit asperiores similique assumenda doloribus rerum vero provident itaque repellat molestias, architecto aut corrupti magnam adipisci natus recusandae culpa, alias neque, quas distinctio! A similique placeat officia distinctio, nam vel molestias odit laudantium. Natus exercitationem eligendi magni sunt dolorum temporibus autem veniam, quae impedit unde at cum quod mollitia aperiam tempora? Consectetur quas minus minima quis? Perferendis pariatur delectus voluptatem reprehenderit. Quo quae, a quia deserunt recusandae accusamus quas harum modi ullam temporibus iste eius? Ea, iusto? Esse minus quod pariatur inventore asperiores repellendus nulla, ex aliquam suscipit atque eum nesciunt laboriosam debitis sit. Labore expedita, accusantium eligendi voluptas totam eveniet nulla, maxime pariatur ex earum facere? Quo culpa consequuntur, commodi aliquid ut molestiae repellat dolores sequi totam exercitationem vitae minima pariatur, esse adipisci molestias doloremque eum obcaecati, sapiente saepe. Accusamus alias facilis neque perspiciatis aspernatur culpa sapiente repudiandae voluptatibus, beatae adipisci architecto repellat, eaque quibusdam laboriosam voluptas odit quam optio est et expedita quidem eum sunt. Inventore fugit commodi eum fuga, repellendus culpa maiores molestiae quis facilis nesciunt? Minima, magnam! Repellat veniam ducimus quam sunt voluptatum, dignissimos pariatur nemo ea tempora sapiente optio asperiores autem fugit est dolor error quisquam nesciunt inventore odit? Provident incidunt est culpa consequatur quaerat alias earum voluptatibus? Maiores omnis reiciendis aut sapiente nostrum, velit, impedit quisquam dolores porro hic minima fugiat unde. Quas laborum recusandae magni fuga, qui fugit quos similique asperiores voluptatum. Similique, repellendus. Sequi magnam sed voluptates culpa et, asperiores voluptatibus iste veritatis praesentium voluptas repudiandae, odit magni nostrum qui tenetur, eaque voluptatum modi enim hic nam? Animi, ducimus veniam ipsa dolores nostrum odit modi fugit maxime dicta facilis possimus! Corrupti reiciendis rerum voluptas! Amet laborum iste doloribus nesciunt expedita distinctio ipsam tempore, est doloremque. Aliquid nisi eaque blanditiis asperiores laudantium maxime vero sed cumque! Non voluptas aspernatur impedit iure corrupti excepturi.</div>
    </div>
    </>
  )
}

export default About